### ISSUE TITLE
Editor shortcuts 

### ISSUE THREAD

**Issue by Rafailong** [ArmandGrillet/Mado#104]
I have used other md editor and all of the have only one thing in common that yours does not have. Editor shortcuts, I mean

Ctrl + b => ** bold **
Ctrl + i => * italic *

and some others, I think that your editor is really cool, mean and lean but it would be nice to add those editor shortcuts.

Thank you for the editor! :smile:

**Comment by ArmandGrillet** [comment]
Theses changes are creating problems with Ctrl + z and Ctrl + y so they won't be applied, sorry.
