### ISSUE TITLE
Translation in Chinese

### ISSUE THREAD

**Issue by hanxi** [ArmandGrillet/Mado#105]
I'd like Mado then haroopad(https://github.com/rhiokim/haroopad). because Mado very
beautiful and simplify.

**Comment by hanxi** [comment]
I think it will.

**Comment by ArmandGrillet** [comment]
Mado can now be localized in Chinese, `src/_locales/zh_CN/messages.json`needs to be written based on `src/_locales/en/messages.json` and [chrome.i18n](https://developer.chrome.com/extensions/i18n).
As I'm not a Chinese speaker you're more than welcome to do it!
