### ISSUE TITLE
Problem new version

### ISSUE THREAD

**Issue by abacoian** [ArmandGrillet/Mado#110]
I was using Mado for simple writing for a few weeks, I like the word count and that I can just hit ctrl s and it works on my chromebook. About a week ago it stopped working, I can open it but when I press any of the buttons nothing happens. I uninstalled and reinstalled and still doesn't work. Please help. Thank you, Ian

**Comment by ArmandGrillet** [comment]
Hey Ian, would it be ok if we share our screen using the Chrome Remote Desktop soon? 
Mado is working on my computer so it would be the best way for me to find the bug.

**Comment by ArmandGrillet** [comment]
I added a reset button in the Settings page, click it and Mado should work perfectly after its restart:
![capture d ecran 2015-01-20 a 08 39 38](https://cloud.githubusercontent.com/assets/2117580/5813578/2163b596-a080-11e4-885b-413277c53e31.png)
The update will come today through the Chrome Web Store, automatically.

**Comment by abacoian** [comment]
I uninstalled and reinstalled, still not working, unfortunatley I can't click the settings button :(

**Comment by ArmandGrillet** [comment]
Mado 0.4.0.3 is here with an automatic reset at launch. If it still does not work please contact me.

**Comment by ArmandGrillet** [comment]
No news and no complains on the Chrome Web Store, issue closed.

**Comment by abacoian** [comment]
I will try to uninstall and reinstall again

Date: Tue, 27 Jan 2015 10:47:13 -0800

**Comment by victorel-petrovich** [comment]
### Hi,

I installed Mado yesterday from Chrome webstore (I have a samsung chromebook), and it I can open it but when I press any of the buttons nothing happens. I uninstalled and reinstalled and still doesn't work. Exactly like the person who opened this issue.  
What I can add is that I can type stuff, but no preview appears.

Please help.

**Comment by ArmandGrillet** [comment]
Hi,

As I don't have a Chromebook the best solution would be to have a session using Chrome Remote Desktop with you to allow me to debug with a Chromebook. If you're OK with this send me a message on Hangout [here](https://plus.google.com/u/0/+ArmandGrillet/posts), I really want to find the bug.

**Comment by ArmandGrillet** [comment]
Please follow [this procedure](https://github.com/ArmandGrillet/Mado/wiki/Use-Mado-as-a-developer) so that I can fix the bugs.

**Comment by victorel-petrovich** [comment]
### Hi Armand,

I followed that procedure, and I reproduced the bug.

#### 1. The errors shown
For `mado.html`, the errors that appeared are: 
```
(x) Failed to load resource: net::ERR_FILE_NOT_FOUND                chrome-extension://dbgcaafokanbkdkegheekbamhgplgfgf/js/lib/Countable.js 
(x) Uncaught ReferenceError: Countable is not defined                 Counter.js:45 
```
For the `background page`, there were no errors displayed.

For curiosity, I also tried to look at the errors when the regular app Mado from chrome webstore was intalled. In this case, right click in the editing part does not offer  "Inspect element" (Only options are : undo, redo, cut, and a couple others. I noted that "Inspect element" does not appear either in other Apps installed from chrome store, while it appears in Extensions from there).  
HOWEVER: after starting Mado ,  inside Extensions page I was able to click on both `mado.html`, and `background page`. The latter did not give errors, while the errors displayed for the first one were (almost) the same as for the unpacked extension:
```	 
(x) Failed to load resource: net::ERR_FILE_NOT_FOUND      chrome-extension://gmmlaihnodfojphcmjeemhaeajaldcdj/js/lib/Countable.js
(x) Uncaught ReferenceError: Countable is not defined      mado.js:3
```

#### 2. The apparent solution

Back to the Unpacked extension: from that `Inspect Element` window, looking at sources, I see that the required `Countable.js` is empty. Navigating to the  install `Mado-master` folder, I noticed that there is a  `countable.js`  but now`Countable.js` file in the respective folder, so I just capitalized the first letter in the name, re-launched the app, and...
**now everything seem to work** ! Editing, buttons, preview, word count button, settings etc.

Victor

![Cheers](file:///home/chronos/user/Downloads/DOWNLOADS/Screenshot%202015-02-23%20at%2012.12.00%20AM.png)

**Comment by ArmandGrillet** [comment]
I can't believe it was something that simple. Anyway, thank you very much!
Mado 0.4.1.1 (with the fix for Chrome OS) is now on GitHub and published on the Chrome Web Store thus the update will be available for everyone today.
