### ISSUE TITLE
click settings twice will popup two subpage.

### ISSUE THREAD

**Issue by hanxi** [ArmandGrillet/Mado#112]
If I click `settings` item, it will popup two subpage, like the screenshot.
![2015-01-31 5 04 07](https://cloud.githubusercontent.com/assets/1185757/5987551/1d1cf188-a96c-11e4-9674-401984ec4757.png)

I think the popup subpage must be one for the same subpage.

**Comment by ArmandGrillet** [comment]
I'm not able to reproduce this bug, I just modified `MoreWindowsManager.js` to delete references of the removed Q&A page, can you please sync the project and try again? 
If the bug is still there check if there is an error in the Chrome console (`right click`-> `Inspect the element`).
