### ISSUE TITLE
desktop application

### ISSUE THREAD

**Issue by benavern** [ArmandGrillet/Mado#115]
Hello! 

I love this chrome application but would like to be independant of chrome and make it a desktop application.

I would like to know if it would be easy to do that with nw.js ? if you plan to do it ?....

Thanks in advance!

**Comment by ArmandGrillet** [comment]
Hi, sorry for the delay. Mado has been developed for Google Chrome, there is no plan to develop it as an independent desktop application.

I saw that you've forked the project, feel free to transform Mado into something that suit your needs better!

**Comment by benavern** [comment]
ok, no problem! 
I forked and looked at the sources but saw that there are some chrome specific scripts.

I decides to try creating my own from scratch :)

thank you for the answer!
