### ISSUE TITLE
Images in file system next to document do not display

### ISSUE THREAD

**Issue by robogeek** [ArmandGrillet/Mado#119]
I'm using Mado to edit files which I use to build my website using AkashaCMS as the website generator.  It means I have a directory structure containing a mix of Markdown and image files.  If it makes a difference, I'm using it on a Chromebook which has been jailbreak'd to run Crouton so I can run command line tools like AkashaCMS.

If I put an image tag into the Markdown, the previewer doesn't display the image.  Instead a message "...filename... Not found" followed by a broken square icon that implies a broken image.

The image tag can be: `<img src="P5170139-700.jpg"/>`
Or the Markdown equivalent: `![](P5170139-700.jpg)`

It gives the same behavior either way.

**Comment by ArmandGrillet** [comment]
This is due to the Google Chrome security policy, it is also due to this policy that we need to ask for galleries when the user selects an image. If you want to display an image that is in the same folder as the file use `![](./P5170139-700.jpg)` and make sure than the folder is one of the gallery.
